apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opensearch
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: logging
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
    cleanupOnFail: true
    force: true
  chart:
    spec:
      chart: opensearch
      sourceRef:
        kind: HelmRepository
        name: opensearch
        namespace: flux-system
      version: "3.3.0"
  values:
    replicas: 1

    singleNode: true

    opensearchJavaOpts: "-Xms512m -Xmx512m"

    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 1Gi

    persistence:
      enabled: true
      storageClass: "monitoring-local-storage"
      size: 5Gi

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

    config:
      opensearch.yml: |
        cluster.name: opensearch-cluster
        network.host: 0.0.0.0
        discovery.type: single-node
        plugins:
          security:
            disabled: true

    extraEnvs:
      - name: DISABLE_INSTALL_DEMO_CONFIG
        value: "true"
      - name: DISABLE_SECURITY_PLUGIN
        value: "true"
