apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-pv
  labels:
    type: local
    app: opensearch
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: monitoring-local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker
  hostPath:
    path: /opt/opensearch-data
    type: DirectoryOrCreate
