{{- if .Values.storageClass.create }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.global.storageClass }}
  labels:
    {{- include "order-app.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
{{- end }}
