apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infrastructure-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/aidaner256/flux-infrastructure.git
  ref:
    branch: main
  secretRef:
    name: flux-git-credentials