apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: logging
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
    cleanupOnFail: true
    force: true
  chart:
    spec:
      chart: fluent-bit
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
      version: "0.54.0"
  values:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    securityContext:
      runAsUser: 0
      runAsGroup: 0
      readOnlyRootFilesystem: true

    config:
      service: |
        [SERVICE]
            Daemon Off
            Flush 1
            Log_Level info
            Parsers_File parsers.conf
            Parsers_File custom_parsers.conf
            HTTP_Server On
            HTTP_Listen 0.0.0.0
            HTTP_Port 2020
            Health_Check On

      inputs: |
        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            multiline.parser docker, cri
            Tag kube.*
            Mem_Buf_Limit 5MB
            Skip_Long_Lines On

        [INPUT]
            Name systemd
            Tag host.*
            Systemd_Filter _SYSTEMD_UNIT=kubelet.service
            Read_From_Tail On

      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Kube_URL https://kubernetes.default.svc:443
            Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
            Kube_Tag_Prefix kube.var.log.containers.
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On
            Buffer_Size 0

        [FILTER]
            Name modify
            Match *
            Remove _p

      outputs: |
        [OUTPUT]
            Name opensearch
            Match kube.*
            Host opensearch-cluster-master.logging.svc.cluster.local
            Port 9200
            Index fluent-bit
            Suppress_Type_Name On
            tls Off
            tls.verify Off
            Retry_Limit 2

        [OUTPUT]
            Name opensearch
            Match host.*
            Host opensearch-cluster-master.logging.svc.cluster.local
            Port 9200
            Index fluent-bit-host
            Suppress_Type_Name On
            tls Off
            tls.verify Off
            Retry_Limit 2

    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
