apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 1m
  path: "./infrastructure/vault/external-secrets/conf"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure-repo
