apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 1m
  path: "./infrastructure/apps/dev/db-postgre/conf"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure-repo
