apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: csi-driver
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: 1.5.4
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
        namespace: vault
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    syncSecret:
      enabled: true
    enableSecretRotation: true