apiVersion: v2
name: order-app
description: A Helm chart for Order App microservice with Kafka, RabbitMQ, MongoDB, and Redis
type: application
version: 1.0.0
appVersion: "1.0.2"
keywords:
  - order-app
  - microservice
  - kafka
  - rabbitmq
  - mongodb
  - redis
  - vault
maintainers:
  - name: DevOps Team
    email: devops@example.com
home: https://github.com/order-app
sources:
  - https://github.com/order-app
