apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: monitoring
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
    cleanupOnFail: true
    force: true
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "78.4.0"
  values:
    grafana:
      initChownData:
        enabled: false
      podSecurityContext:
        runAsUser: 472
        runAsGroup: 472
        fsGroup: 472
      enabled: true
      admin:
        existingSecret: grafana-admin-secret
        userKey: admin-user
        passwordKey: admin-password
      persistence:
        enabled: true
        storageClassName: monitoring-local-storage
        size: 5Gi
        selector:
          matchLabels:
            app: grafana
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana.local
        path: /
        pathType: Prefix

    prometheus:
      initChownData:
        enabled: true
        securityContext:
          runAsUser: 0
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - prometheus.local
        paths:
          - /
        pathType: Prefix
      prometheusSpec:
        securityContext:
          runAsUser: 65534
          runAsGroup: 65534
          fsGroup: 65534
          fsGroupChangePolicy: "OnRootMismatch"
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: monitoring-local-storage
              accessModes: ["ReadWriteOnce"]
              selector:
                matchLabels:
                  app: prometheus
              resources:
                requests:
                  storage: 10Gi

    alertmanager:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - alertmanager.local
        paths:
          - /
        pathType: Prefix
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: monitoring-local-storage
              accessModes: ["ReadWriteOnce"]
              selector:
                matchLabels:
                  app: alertmanager
              resources:
                requests:
                  storage: 2Gi
