apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-kustomization.yaml
  # - opensearch-kustomization.yaml
  # - kibana-kustomization.yaml
  # - fluent-bit-kustomization.yaml
