apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 1m
  path: "./infrastructure/monitoring/prometheus/conf"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure-repo
  dependsOn:
    - name: metallb
    - name: external-secrets
    - name: vault
