apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m
  path: "./infrastructure/platform/ingress-nginx/conf"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure-repo
  dependsOn:
    - name: prometheus
