apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1m
  path: "./infrastructure/platform/metallb/conf"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure-repo
